import express from "express"; //Import for server
import multer from 'multer'; //Middlewere for handling files
import cors from 'cors'; //Middlewere for requests
import path from 'path';
import bcrypt from 'bcrypt'; //For Hashing admin password
import jwt from 'jsonwebtoken'; //For saving tokens
import cookieParser from 'cookie-parser'; //HTTP only cookie
import fs from 'fs'; //File system
import { fileURLToPath } from 'url';
import { exec } from 'child_process'; //For running JS scripts in this case acCal, schedule extractors
// import connectDB from "./db.js"; //Dependency for db.js on our file system
// import Calendar from "./models/schema.js"; //imporst schema.js to server

const __filename = fileURLToPath(import.meta.url);  //default filePaths
const __dirname = path.dirname(__filename);

//Hardcoded credencials
const username = "admin"
const hashedPassword = `$2b$10$.KGaGxxvvV1CaEZLrGbxVOeKa7juuHcFMPyPAbdEaOjLCTYeQ6Qpa`

//create app with express
const app = express();


//If /uploads doesn't exist, create it
if (!fs.existsSync('./uploads')) {
    fs.mkdirSync('./uploads');
}

//Gets info for uploading file to /uploads
const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, 'uploads/');
    },
    filename: (req, file, cb) => {

        const uniqueName = file.originalname;
        cb(null, uniqueName);
    }
});

//saves the file to /upload
const upload = multer({ storage: storage });

// connectDB(); //connect to db through db.js

app.use(cors()); //use the middlewere 
app.use(express.json()); //use json option with express
app.use(cookieParser()); //use http cookie


app.use(express.static(path.join(__dirname, 'public'))); //express will use the public folder as public domain

app.get("/", (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'html', 'index.html')); // localhost::xxxx/ is index.html
});

app.get("/politiki-cookies", (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'html', 'politiki-cookies.html')); // localhost::xxxx/politiki-cookies takes you to politiki-cookies
});

app.get("/loginForAdmin", (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'html', 'login.html')); // localhost::xxxx/loginForAdmin takes you to login.admin
});

app.use('/jsonData', express.static(path.join(__dirname, 'jsonData'))); // Possible vaulnerabily may need fixing, makes /jsonData static public domain


//function to generate passowrd hash

//function to see the hash
// async function generateHash() {
//     // const salt = await bcrypt.genSalt(10);
//     // const hash = await bcrypt.hash('password', salt);
//     // await bcrypt.compare(password, valid_user.password)
//     console.log(await bcrypt.compare(`password`, `$2b$10$.KGaGxxvvV1CaEZLrGbxVOeKa7juuHcFMPyPAbdEaOjLCTYeQ6Qpa`));
// }
// generateHash();


//verifies that user has a token (AKA is logged in)
const verifyToken = (req, res, next) => {
    const token = req.cookies.token;

    if (!token) {
        return res.redirect('/loginForAdmin');
    }

    try {
        jwt.verify(token, 'mfmfx123');
        next();
    } catch (err) {
        res.clearCookie('token');
        res.redirect('/loginForAdmin');
    }
};


//Merges the .json files generated by the pipeline to a merged_shedule.json 
app.post("/sendData", verifyToken, async (req, res) => {
    try {
        const springPath = path.join(__dirname, 'jsonData', 'spring_schedule.json');
        const winterPath = path.join(__dirname, 'jsonData', 'winter_schedule.json');
        const mergedPath = path.join(__dirname, 'jsonData', 'merged_schedule.json');

        const springData = JSON.parse(fs.readFileSync(springPath, 'utf8'));
        const winterData = JSON.parse(fs.readFileSync(winterPath, 'utf8'));

        const combinedData = [...springData, ...winterData];

        // Save locally instead of using MongoDB
        fs.writeFileSync(mergedPath, JSON.stringify(combinedData, null, 2));

        res.status(201).json({
            message: "Database updated from local JSON files",
            count: combinedData.length
        });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

app.post("/sendLabData", verifyToken, async (req, res) => {
    try {
        const springPath = path.join(__dirname, 'jsonData', 'spring_labs.json');
        const winterPath = path.join(__dirname, 'jsonData', 'winter_labs.json');
        const mergedPath = path.join(__dirname, 'jsonData', 'merged_labs.json');

        const springData = fs.existsSync(springPath) ? JSON.parse(fs.readFileSync(springPath, 'utf8')) : [];
        const winterData = fs.existsSync(winterPath) ? JSON.parse(fs.readFileSync(winterPath, 'utf8')) : [];

        const combinedData = [...springData, ...winterData];

        fs.writeFileSync(mergedPath, JSON.stringify(combinedData, null, 2));

        res.status(201).json({
            message: "Lab Database updated",
            count: combinedData.length
        });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});


//Merges the .json files generated by the pipeline to a merged_exams.json 
app.post("/sendExamData", verifyToken, async (req, res) => {
    try {
        const makeUpPath = path.join(__dirname, 'jsonData', 'make_up_exams.json');
        const semesterPath = path.join(__dirname, 'jsonData', 'semester_exams.json');
        const mergedPath = path.join(__dirname, 'jsonData', 'merged_exams.json');

        // Check if files exist before reading; default to empty arrays if they don't
        const makeUpData = fs.existsSync(makeUpPath) ? JSON.parse(fs.readFileSync(makeUpPath, 'utf8')) : [];
        const semesterData = fs.existsSync(semesterPath) ? JSON.parse(fs.readFileSync(semesterPath, 'utf8')) : [];

        const combinedData = [...makeUpData, ...semesterData];

        // Save locally
        fs.writeFileSync(mergedPath, JSON.stringify(combinedData, null, 2));

        res.status(201).json({
            message: "Database updated from local JSON files",
            count: combinedData.length
        });
    } catch (err) {
        // This will now only catch JSON parsing errors or write permissions errors
        res.status(400).json({ error: err.message });
    }
});

app.post("/getLabs", async (req, res) => {
    try {
        const { semester } = req.body;
        const labsPath = path.join(__dirname, 'jsonData', 'merged_labs.json');

        if (!fs.existsSync(labsPath)) {
            return res.status(404).json({ error: "Labs file not found" });
        }

        const data = JSON.parse(fs.readFileSync(labsPath, 'utf8'));

        //("1", "6", ή "General")
        const filteredLabs = data.filter(lab => String(lab.semester) === String(semester));

        res.status(200).json(filteredLabs);
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});


//used in calendar.js and admin.js to get all the title names of courses based on the given semester
app.post("/getSemester", async (req, res) => {
    try {
        const { semester } = req.body; //req = semester (e.g 1, 2, 6)
        const mergedPath = path.join(__dirname, 'jsonData', 'merged_schedule.json');

        const data = JSON.parse(fs.readFileSync(mergedPath, 'utf8'));

        const titles = data
            .filter(course => String(course.semester) === String(semester))
            .map(course => ({ title: course.title }));

        //Send the data back to the client!
        res.status(200).json({ titles });
    }
    catch (err) {
        res.status(400).json({ error: err.message });
    }
});

// used in calendar.js to fetch course that match the user's search
app.post("/getSearch", async (req, res) => {
    try {

        const { search, mode } = req.body // whatever the user typed into the searchbar, plus which mode the sidebar is in
        var dataPath; // Declaring this here so it can be used for every mode
        var titles; // We will store the matching titles here

        // Depending on the mode we pull data from the respective json file
        if (mode === "Μαθήματα") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_schedule.json');
            const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            titles = data
                .filter(course => String(course.title).includes(String(search).toUpperCase())) // Filtering so we only return the results that match the search. We use "includes"
                .map(course => ({ title: course.title }));

        } else if (mode === "Εξεταστική") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_exams.json');
            const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            titles = data
                .filter(exam => String(exam.title).includes(String(search).toUpperCase())) // Filtering so we only return the results that match the search. We use "includes"
                .map(exam => ({ title: exam.title }));

        } else if (mode === "Εργαστήρια") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_labs.json');
            const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            titles = data
                .filter(lab => String(lab.name).includes(String(search).toUpperCase())) // Filtering so we only return the results that match the search. We use "includes"
                .map(lab => ({ title: lab.name }));

        }

        res.status(200).json({ titles });  // Returning the titles

    } catch (err) {
        res.status(400).json({ error: err.message }); // Big beautiful error
    }
})

// Used to populate the selection boxes in the filter menu
app.post("/getTeachersAndRooms", async (req, res) => {

    try {
        const { mode } = req.body // The mode the sidebar is in i.e. "Μαθηματα"
        var dataPath = []; // Declaring this here so it can be used for every mode
        var teachers = []; // We will store the unique teachers here
        var rooms = []; // We will store the unique rooms here

        // Depending on the mode we pull data from the respective json file
        if (mode === "Μαθήματα") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_schedule.json');
            const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            teachers = [...new Set(data.map(item => item.professor).flat())]; // Making sure we dont get duplicates with Set()
            rooms = [...new Set(data.map(item => item.lectureHall).flat())]; // lecture halls and professors are arrays so we use .flat() to take the single items
        } else if (mode === "Εξεταστική") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_exams.json');
            const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            rooms = [...new Set(data.map(item => item.lectureHall).flat())];


        } else if (mode === "Εργαστήρια") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_labs.json');
            const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

            // Here the rooms are nested into the kab items so we need flatMap to get into the nested arrays
            const allLabHalls = data.flatMap(lab =>
                lab.data.map(d => d.labhall)
            );
            rooms = [...new Set(allLabHalls)];

        }

        res.status(200).json({ teachers, rooms });  // Returning the teachers and the rooms
    } catch (err) {
        res.status(400).json({ error: err.message }); // Big beautiful error
    }

})

app.post("/getFiltered", async (req, res) => {

    try {
        const { teacher, room, mode } = req.body;

        var titles = []; // storing the titles
        var dataPath; // Declaring this here so it can be used for every mode
        var data;

        // Depending on the mode we pull data from the respective json file
        if (mode === "Μαθήματα") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_schedule.json');
            data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));


        } else if (mode === "Εξεταστική") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_exams.json');
            data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
        } else if (mode === "Εργαστήρια") {
            dataPath = path.join(__dirname, 'jsonData', 'merged_labs.json');
            data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
        }

        if (data) {
            // We now need to find the data that match our filters
            const filtered = data.filter(item => {
                let matchTeacher = true; // Since one of the filters can be blank, we start with "true" 
                let matchRoom = true;

                if (mode === "Μαθήματα") {
                    // Check if the teacher is in the teacher array of the item
                    if (teacher != "Διδάσκων") {
                        matchTeacher = item.professor && item.professor.includes(teacher);
                    }

                    //Check if the room is in the room array of the item
                    if (room != "Αίθουσα") {
                        matchRoom = item.lectureHall && item.lectureHall.includes(room);
                    }
                }
                else if (mode === "Εξεταστική") {
                    //Check if the room is in the room array of the item
                    if (room != "Αίθουσα") {
                        matchRoom = item.lectureHall && item.lectureHall.includes(room);
                    }
                }
                else if (mode === "Εργαστήρια") {
                    //Check if the room is in the room array of the item, here the rooms are nested inthe item we use .some(). Even if one room matches the item is kept
                    if (room) {
                        matchRoom = item.data && item.data.some(d => d.labhall === room);
                    }

                }
                // Only keeping the class if both are true
                return matchTeacher && matchRoom;
            });

            // 3. Map to titles (handling 'title' vs 'name' keys)
            titles = filtered.map(item => item.title || item.name);
        }

        res.status(200).json({ titles });  // Returning the titles

    } catch (err) {
        res.status(400).json({ error: err.message }); // Big beautiful error
    }

})

//used in calendar.js and admin.js to get all the data of a spesific course/class 
app.post("/getClass", async (req, res) => {
    try {
        const { title } = req.body;
        const mergedPath = path.join(__dirname, 'jsonData', 'merged_schedule.json');

        const data = JSON.parse(fs.readFileSync(mergedPath, 'utf8'));

        // Find the specific course
        const scheduleData = data.find(course => course.title === title);

        if (!scheduleData) {
            return res.status(404).json({ message: "Class not found" });
        }

        const mappedSchedules = scheduleData.daysOfWeek.map((day, index) => {
            return {
                title: scheduleData.title,
                day: day,
                lectureHall: scheduleData.lectureHall[index],
                start: scheduleData.startTime[index],
                end: scheduleData.endTime[index],
                color: scheduleData.color,
                professor: scheduleData.professor,
                semester: scheduleData.semester
            };
        });

        res.status(200).json({ schedules: mappedSchedules });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

// Gets one specific lab
app.post("/getLab", async(req,res) => {

    try{
        const { title } = req.body;

        console.log(title)

        const mergedPath = path.join(__dirname, 'jsonData', 'merged_labs.json');

        console.log(mergedPath)
        const data = JSON.parse(fs.readFileSync(mergedPath, 'utf8'));

        console.log(data)
        const lab = data.find(lab => lab.name === title);
        console.log(lab)

        res.status(200).json(lab)

    }catch (err) {
        res.status(400).json({ error: err.message });
    }

})

// Used in calendar.js to get all the data for an exam tied to a specific course
app.post("/getExam", async (req, res) => {
    try {
        const { title } = req.body;

        const baseTitle = title.split('(')[0].trim();

        const examPath = path.join(__dirname, 'jsonData', 'merged_exams.json');

        const data = JSON.parse(fs.readFileSync(examPath, 'utf8'));


        // Find the exam associated with the specific course title
        const examData = data.find(exam => exam.title === title) ||
            data.find(exam => exam.title === baseTitle);

        if (!examData) {
            return res.status(404).json({ message: "Exam not found" });
        }

        res.status(200).json({ exam: examData });

    } catch (err) {
        res.status(400).json({ error: err.message });
    }
})

// Gets all exams for a specific semester
app.post("/getSemesterExams", async (req, res) => {
    try {
        const { semester } = req.body;
        const examPath = path.join(__dirname, 'jsonData', 'merged_exams.json');

        // Read and parse the exam JSON file
        const data = JSON.parse(fs.readFileSync(examPath, 'utf8'));

        // Filter out only the exams that match the requested semester
        // We use String() to safely handle numbers vs strings (e.g., 7 vs "7")
        const semesterExams = data.filter(exam => String(exam.semester) === String(semester));

        // Send the filtered array directly back to the frontend
        return res.status(200).json(semesterExams);

    } catch (err) {
        console.error("Error fetching semester exams:", err);
        res.status(400).json({ error: err.message });
    }
});

app.post("/getSemesterOfExams", async (req, res) => {
    try {
        const semesterPath = path.join(__dirname, 'jsonData', 'semester_exams.json');
        const makeUpPath = path.join(__dirname, 'jsonData', 'make_up_exams.json');

        // 1. Check normal semester exams first
        if (fs.existsSync(semesterPath)) {
            const exams = JSON.parse(fs.readFileSync(semesterPath, 'utf8'));

            // Check if valid data exists
            if (Array.isArray(exams) && exams.length > 0 && exams[0].semester) {
                const isWinter = (exams[0].semester % 2 !== 0);
                return res.status(200).json(isWinter);
            }
        }

        //If normal exams don't exist or are empty, check make-up exams
        if (fs.existsSync(makeUpPath)) {
            const makeUpExams = JSON.parse(fs.readFileSync(makeUpPath, 'utf8'));

            // Check if valid data exists
            if (Array.isArray(makeUpExams) && makeUpExams.length > 0 && makeUpExams[0].semester) {
                const isWinter = (makeUpExams[0].semester % 2 === 0);
                return res.status(200).json(isWinter);
            }
        }

        //If neither file exists or both are empty
        return res.status(404).json({ error: "No valid exams found in either file" });

    } catch (error) {
        console.error("Error fetching exams semester:", error);
        res.status(500).json({ error: "Internal server error" });
    }
});

//request used in login.js to 
app.post("/login", async (req, res) => {
    try {
        const { username: incomingUsername, password } = req.body; //req = usermana and password from user

        if (incomingUsername !== username) {  //validates username with hardcoded username
            return res.status(400).json({ message: "Username not found!" });
        }

        const isPasswordCorrect = await bcrypt.compare(password, hashedPassword); //bcrypts compares the hash of the password with the hardcoded hash

        if (!isPasswordCorrect) {
            return res.status(400).json({ message: "Wrong password!" });
        }


        const token = jwt.sign( //creates a token that expires in 1 hour (for security)
            { userId: "static_admin_id", username: username },
            'mfmfx123',
            { expiresIn: '1h' }
        );

        res.cookie('token', token, {    //saves token in http only cookie so token doesn't get stored in local history and storage (better for security)
            httpOnly: true,
            secure: false,
            maxAge: 3600000
        });

        return res.status(200).json({ message: "Login successful", username: username });


    }
    catch (err) {
        res.status(500).json({ error: err.message });
    }
});

//Calls multer with upload.single() to get info to upload the file
app.post('/upload', verifyToken, upload.single('uploadedFile'), (req, res) => {

    //req and res used for messages to user, no saving is done here
    if (!req.file) {
        return res.status(400).send('No file uploaded.');
    }

    res.json({
        message: "Επιτυχία!",
        fileName: req.file.filename
    });
});

//----------THE AGIA TETRADA OF PIPELINES------------------

//request used in admin.js to run extractor after uploading a schedule
app.post(`/run_schedule_extractor`, verifyToken, (req, res) => {
    exec('node schedule_extractor.js', (error, stdout, stderr) => {
        if (error) {
            console.error(`Error: ${error.message}`);
            return res.status(500).send('Extraction failed');
        }
        console.log(`Output: ${stdout}`);
        res.send('Extractor executed successfully');
    });
});

//request used in admin.js to run extractor after uploading labs
app.post(`/run_labs_extractor`, verifyToken, (req, res) => {
    exec('node labs_extractor.js', (error, stdout, stderr) => {
        if (error) {
            console.error(`Error: ${error.message}`);
            return res.status(500).send('Extraction failed');
        }
        console.log(`Output: ${stdout}`);
        res.send('Extractor executed successfully');
    });
});

//request used in admin.js to run extractor afte uploading an academic calendari
app.post(`/run_acCal_extractor`, verifyToken, (req, res) => {
    exec('node acCal_extractor.js', (error, stdout, stderr) => {
        if (error) {
            console.error(`Error: ${error.message}`);
            return res.status(500).send('Extraction failed');
        }
        console.log(`Output: ${stdout}`);
        res.send('Extractor executed successfully');
    });
});

//request used in admin.js to run extractor afte uploading an exam
app.post(`/run_exams_extractor`, verifyToken, (req, res) => {
    exec('node exams_extractor.js', (error, stdout, stderr) => {
        if (error) {
            console.error(`Error: ${error.message}`);
            return res.status(500).send('Extraction failed');
        }
        console.log(`Output: ${stdout}`);
        res.send('Extractor executed successfully');
    });
});

//-------------------------------------------------------------------------

//admin.html made private using verifyToken only accesable after login in
app.get("/admin", verifyToken, (req, res) => {
    res.sendFile(path.join(__dirname, 'private', 'admin.html'));
})

//admin.js made private using verifyToken only accesable after login in
app.get("/secure-admin-script.js", verifyToken, (req, res) => {
    res.sendFile(path.join(__dirname, 'private', 'admin.js'));
});


//eniciates app listening on port 8000
const PORT = 8000;
app.listen(PORT, () => {
    console.log(`Server live at http://localhost:${PORT}`);
});


//gets the new data of the course and updates the program json file
app.post("/updateCourse", async (req, res) => {
    try {
        const {
            title,
            daysOfWeek,
            startTime,
            endTime,
            lectureHall,
            semester,
            professor
        } = req.body;

        const mergedPath = path.join(__dirname, 'jsonData', 'merged_schedule.json');

        const data = JSON.parse(fs.readFileSync(mergedPath, 'utf8'));

        //find the specific course 
        const courseIndex = data.findIndex(course => course.title === title);

        if (courseIndex === -1) {
            return res.status(404).json({ message: "Course not found" });
        }

        //replace course data 
        data[courseIndex] = {
            ...data[courseIndex],
            title,
            daysOfWeek,
            startTime,
            endTime,
            lectureHall,
            semester,
            professor
        };

        fs.writeFileSync(mergedPath, JSON.stringify(data, null, 2), 'utf8');

        res.json({ message: "Course updated successfully!" });

    } catch (err) {
        console.error(err);
        res.status(500).json({ message: err.message });
    }
});

//gets the new data of the course and updates the exam json file
app.post("/updateExamCourse", async (req, res) => {
    try {
        const {
            title,
            date,
            startTime,
            endTime,
            lectureHall,
            semester,
            division
        } = req.body;

        const mergedPath = path.join(__dirname, 'jsonData', 'merged_exams.json');

        const data = JSON.parse(fs.readFileSync(mergedPath, 'utf8'));

        //find the specific course 
        const courseIndex = data.findIndex(course => course.title === title);

        if (courseIndex === -1) {
            return res.status(404).json({ message: "Exam not found" });
        }

        //replace course data 
        data[courseIndex] = {
            ...data[courseIndex],
            title,
            date,
            startTime,
            endTime,
            lectureHall,
            semester,
            division
        };

        fs.writeFileSync(mergedPath, JSON.stringify(data, null, 2), 'utf8');

        res.json({ message: "Exam updated successfully!" });

    } catch (err) {
        console.error(err);
        res.status(500).json({ message: err.message });
    }
});


//gets the new data of the lab and updates the lab json file
app.post("/updateLab", async (req, res) => {
    try {
        const {
            name,
            semester,
            data
        } = req.body;

        const mergedPath = path.join(__dirname, 'jsonData', 'merged_labs.json');

        const labs = JSON.parse(fs.readFileSync(mergedPath, 'utf8'));

        //find the specific course 
        const labIndex = labs.findIndex(lab => lab.name === name);

        if (labIndex === -1) {
            return res.status(404).json({ message: "Labs not found" });
        }

        //replace course data 
        labs[labIndex] = {
            ...labs[labIndex],
            name,
            semester,
            data
        };

        fs.writeFileSync(mergedPath, JSON.stringify(labs, null, 2), 'utf8');

        res.json({ message: "Labs updated successfully!" });

    } catch (err) {
        console.error(err);
        res.status(500).json({ message: err.message });
    }
});

app.get('/download-schedule', (req, res) => {
    // Safely construct the exact path to the single file
    const file = path.join(__dirname, 'uploads', 'schedule.pdf');
    
    // res.download() forces the browser to download it with a specific name
    res.download(file, 'University_Schedule.pdf', (err) => {
        if (err) {
            console.error("Error downloading file:", err);
            res.status(404).send("File not found.");
        }
    });
});

app.get('/download-exams', (req, res) => {
    // Safely construct the exact path to the single file
    const file = path.join(__dirname, 'uploads', 'exams.pdf');
    
    // res.download() forces the browser to download it with a specific name
    res.download(file, 'University_Exams.pdf', (err) => {
        if (err) {
            console.error("Error downloading file:", err);
            res.status(404).send("File not found.");
        }
    });
});


// Used in admin.js to get all the data for the academic calendar
app.get("/getAcademicCalendar", (req, res) => {

    try {

        const filePath = path.join(__dirname,"jsonData","academic_calendar.json");

        if (!fs.existsSync(filePath)) {
            return res.status(404).json({message: "Academic calendar file not found"});
        }

        const data = JSON.parse(fs.readFileSync(filePath, "utf8"));

        res.status(200).json(data);

    } catch (error) {
        console.error(error);

        res.status(500).json({
            message: "Failed to load academic calendar"
        });
    }

});


//gets the new data of the academic calendar and updates the academic calendar json file
app.post("/updateAcademicCalendar", (req, res) => {

    try {

        const updatedCalendar = req.body;

        const filePath = path.join(__dirname,"jsonData","academic_calendar.json");

        if (
            !updatedCalendar.academic_year ||
            !Array.isArray(updatedCalendar.semesters) ||
            !Array.isArray(updatedCalendar.holidays) ||
            !Array.isArray(updatedCalendar.exam_periods)
        ) {
            return res.status(400).json({message: "Invalid academic calendar format"});
        }

        fs.writeFileSync(filePath,JSON.stringify(updatedCalendar, null, 2),"utf8");

        res.status(200).json({message: "Academic calendar updated successfully!"});

    } catch (error) {

        console.error(error);

        res.status(500).json({message: "Failed to save academic calendar"});

    }

});


app.use((req, res) => {
    res.status(404).sendFile(path.join(__dirname, 'public', 'html', '404.html'));
});